# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number_of_times', models.IntegerField()),
                ('attendance', models.CharField(choices=[('attend', '出席'), ('absent', '欠席'), ('late', '遅刻'), ('unknown', '不明')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('period', models.IntegerField()),
                ('day', models.CharField(choices=[('Mon', '月'), ('Tue', '火'), ('Wed', '水'), ('Thu', '木'), ('Fri', '金'), ('Sat', '土'), ('Sun', '日')], max_length=3)),
                ('absence', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='cms.Subject', verbose_name='科目'),
        ),
    ]
