# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='absence',
            field=models.CharField(choices=[('attend', '出席'), ('absent', '欠席'), ('late', '遅刻'), ('unknown', '不明')], default='unknown', max_length=7, verbose_name='出席状況'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='classes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='late',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='number_of_times',
            field=models.IntegerField(verbose_name='授業回数'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='day',
            field=models.CharField(choices=[('Mon', '月'), ('Tue', '火'), ('Wed', '水'), ('Thu', '木'), ('Fri', '金'), ('Sat', '土')], max_length=3, verbose_name='曜日'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='period',
            field=models.IntegerField(verbose_name='時限'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=50, verbose_name='科目名'),
        ),
    ]
