# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20160210_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='absence',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='late',
        ),
    ]
