# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20160210_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='number_of_times',
            new_name='times',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='name',
        ),
    ]
